name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2  # Utilisez la version stable la plus récente
      with:
        php-version: '8.0'
        extensions: mbstring, bcmath, mysqli  # Assurez-vous d'installer l'extension mysqli pour MySQL
        coverage: none  # Si vous n'avez pas besoin de couverture de code

    - uses: actions/checkout@v4

    - name: Copy .env
      run: |
        if [ ! -f .env ]; then
          cp .env.example .env
        fi

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 775 storage bootstrap/cache  # Utilisez des permissions plus sécurisées

    - name: Start MySQL service
      run: sudo service mysql start  # Démarre le service MySQL sur l'instance GitHub Actions

    - name: Set up Database for Testing
      run: |
        mysql -e "CREATE DATABASE IF NOT EXISTS school_management;"
        mysql -e "USE school_management;"
        # Exécuter les migrations si nécessaire
        php artisan migrate --env=testing

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: school_management
        DB_USERNAME: root
        DB_PASSWORD: ''
      run: php artisan test --env=testing
