name: Laravel

on: [push, pull_request]

jobs:
  laravel:
    runsflows/laravel.yml` file to use a PHP version compatible with the package requirements. For example, update the-on: ubuntu-latest

    steps:
    - uses: actions PHP version to 8.2.

```yaml
name: Laravel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu/checkout@v2
    - name: Set up PHP
      uses: shiv-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORDammathur/setup-php@v2
      with:
        php-version:: password
        ports:
          - 3306 8.2
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: php artisan test:3306
        options: >-
          --health-cmd="
